language: ruby
rvm:
- 2.1
node_js:
- '6'
install: npm install
script: npm start
env:
  matrix:
  - secure: npsS8l4ESUEoB9sm2eGgp4ig9gW+Xjoo4AdG0rbwB7/utxh1jNJI4gZGT90TqJ6rDjO9d/vbvRuUL7udzbUFevta/P1JsQH1h0uE5ECOmYOAuXkPw86wVLtwSc+OxxoqFmEVO37R/UNI/J2yeGPUVdMUxEUPHwKw819r+U0U/yU=
  - secure: oCajm2G3G4m+hgOBnf7EFOlEc4Y878i8SxLuOEZIT9dEUh/nU+jLcn/cBtbepBZFE+b67Y2+0g1seqGLCCYsBjULoMN/vLPK4m9bHN6alYKzTOEZVKWeKVPYUSIHrFeBB3+Hyf/uli07+o8e1/CJioDYX4DmwqngDx1UD9+ekII=
