language: ruby
rvm:
- 2.1
node_js:
- '6'
install: npm install
script: npm start
env:
  global:
  - secure: rUVwShnmmXN59Si1Qcbrget8xhNpIGdwXfgYW/YX01rCqhBGOaeSz3LL474L9J2kx9pU6ABk6BjzuyTvdcy1vP+XC6edeA0UuTPnS5pZnLYRVdkk8GkMvRPRAICCSQ/cnU4dEUT2jS/5KKAClLpFj69MF0Sf55IZbkXY+WEtR8k=
  - secure: QjvDXg5MZ+mkTdo4+n1XXj6XnL3yBYK8yMYaJNZFlQP9zsdZs79HaZiAfVE3y0n/yQ5oFrpIFD1laDYmmNxlta8ZDvSKvcCO/qoGhkbBOyAIRujYRzFjEJTy5uLyoKItkMdqjkL2L0PWdhs0m3Yx3MzJb3mlsNBDKCBclSRCmt8=
