baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://monks.co" # the base hostname & protocol for your site

permalink: "/:title/index.html"

name: "Andrew Monks"

excerpt_separator: <!--more-->

# Build settings
markdown:    redcarpet
highlighter: pygments

sass:
  sass_dir: _sass

paginate: 3

bio: |+
  I try to help non-technical people engage meaningfully and productively with
  computers. I enjoy writing both code and prose.

  I live in Chicago, IL.
