baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://monks.co" # the base hostname & protocol for your site

permalink: "/:title/index.html"

name: "Andrew Monks"

# Build settings
markdown: "kramdown"

paginate: 2

bio: |+
  I try to help non-technical people engage meaningfully and productively with
  computers. I enjoy writing both code and prose.

  I'm also the proprietor of [Belgian Man Records](http://belgianman.com). I
  draw from 8 years of experience building an active community around Belgian
  Man.

  I was born in Ithaca, NY, raised around Concord, MA, and educated at the
  School of the Art Institute of Chicago.
