baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://monks.co" # the base hostname & protocol for your site

permalink: "/:title/index.html"

name: "Andrew Monks"

# Build settings
markdown: "kramdown"
paginate: 700

bio: |+
  I'm a web designer and product designer based in Chicago, IL, and the
  proprietor of [Belgian Man Records](http://belgianman.com). In my work, I draw
  from 8 years of experience building a community around Belgian Man to build
  things that draw people closer together.
  
  I made my first website in 1999. I was seven. I first explored
  hardware building electronic musical instruments for my band, the [Big
  Trucks](http://belgianman.com/trucks) in middle school. I was born in
  New York and educated at the School of the Art Institute of Chicago.
  
  You can catch me on [Facebook](http://facebook.com/andrewmonks).
