baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://monks.co" # the base hostname & protocol for your site

permalink: "/:title"

name: "Andrew Monks"

excerpt_separator: <!--more-->

# Build settings
markdown:    redcarpet
highlighter: pygments
gems:
  - jemoji

sass:
  sass_dir: _sass

paginate: 3

bio: |+
  I try to make technology less frightening.

footer: |+
  &laquo; &there4;&int;&there4;&int;&there4;&int;&there4;&int;&diams;&int;&there4;&int;&there4;&int;&there4;&int;&there4; &raquo;
