baseurl: ""
url: "http://monks.co"
permalink: "/:title"
excerpt_separator: "<!--more-->"
markdown: "kramdown"
collections:
  letters:
    output: true
media:
  image-class: "w-100"
sass:
  sass_dir: "_sass"
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "_letters"
    values:
      layout: "letter"
      permalink: ":title/index.html"
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: ":title/index.html"
cats:
  bmr: "belgian man records"
  clojure: "clojure"
  code: "code"
  featured: "featured"
  game: "games"
  graphic: "graphics"
  hardware: "hardware"
  howto: "how-tos"
  interaction: "interaction"
  javascript: "javascript"
  joke: "jokes"
  music: "music"
  of: "open frameworks"
  physical: "physical"
  print: "print"
  ruby: "ruby"
  performance: "performance"
  three: "3d"
  video: "video"
  website: "website"
  writing: "writing"
